name: Rust

on: [push, pull_request,workflow_dispatch]

permissions:
  id-token: write
  contents: read
  attestations: write 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile

    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v5

    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.TOKEN1 }}
      run: |
        echo "$SUPER_SECRET"
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
    - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: target/${{ matrix.BUILD_TARGET }}/testGitHubActions1
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: rustTestProgram
        path: target/${{ matrix.BUILD_TARGET }}/testGitHubActions1

