name: Rust

on: [push, pull_request,workflow_dispatch]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: rustTestProgram
        path: target/${{ matrix.BUILD_TARGET }}/testGitHubActions1

#    - name: Archive (${{ env.display_name }})
#      uses: actions/upload-artifact@v4
#      with:
#        name: artifact-${{ env.artifact_name }}
#        path: ${{ env.build_dir }}/artifacts
